version: '3.6'

services: 
  api:
    container_name: api
    build: .
    volumes: 
        - .:/usr/src
    ports: 
        - 8080:8080
    command: npm start
    links: 
        - db
  db:
    image: mongo
    container_name: db
    volumes:
        - /database:/data/db
    ports: 
        - 27017:27017
