version: '3.6'

services: 
  api:
    container_name: api
    build: .
    volumes: 
        - .:/usr/src/app
    ports: 
        - 8080:8080
    # working_dir: "/usr/src/app/"
    command: "npm install && npm start"
    links: 
        - db
    # tty: true
  db:
    image: mongo
    container_name: db
    volumes:
        - /database:/data/db
    ports: 
        - 27017:27017
    # restart: unless-stopped
    # tty: true
